# Site settings
title: Shane Brunson
email: brunson.ws@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog to document my journey through JavaScript, as well as other
  topics I find interesting.
baseurl: ""
url: wsbrunson.com # the base hostname & protocol for your site
twitter_url: https://twitter.com/wsbrunson
github_url:  https://github.com/wsbrunson

# Build settings
markdown: kramdown
