# Site settings
title: Shane Brunson
email: brunson.ws@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog to document my journey through JavaScript, as well as other
  topics I find interesting.
baseurl: ""
url: wsbrunson.com # the base hostname & protocol for your site
twitter_username: wsbrunson
github_username:  wsbrunson

# Build settings
markdown: kramdown
